# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_HOST: postgres
  POSTGRES_DB: custom_db
  POSTGRES_USER: custom_user
  POSTGRES_PASSWORD: custom_pass

before_script:
  - export TEST_DB_HOST=$POSTGRES_HOST
  - export TEST_DB_USER=$POSTGRES_USER
  - export TEST_DB_PASS=$POSTGRES_PASSWORD
  - export TEST_DB_SCHEMA=$POSTGRES_DB
  - export TEST_DB_PORT=5432


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install

unit_tests:
  stage: test
  script:
    - npm run test:cov

e2e_tests:
  stage: test
  script:
    - npm run test:e2e
