image: node:latest

services:
  - postgres:latest

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_HOST: postgres
  POSTGRES_DB: custom_db
  POSTGRES_USER: custom_user
  POSTGRES_PASSWORD: custom_pass

before_script:
  - export TYPEORM_CONNECTION=postgres
  - export TYPEORM_HOST=$POSTGRES_HOST
  - export TYPEORM_USERNAME=$POSTGRES_USER
  - export TYPEORM_PASSWORD=$POSTGRES_PASSWORD
  - export TYPEORM_DATABASE=$POSTGRES_DB
  - export TYPEORM_PORT=5432
  - export TYPEORM_SYNCHRONIZE=true
  - export TYPEORM_LOGGING=true
  - export TYPEORM_ENTITIES=src/**/**.entity{.ts,.js}
  - export TYPEORM_MIGRATIONS_TABLE_NAME=custom_migration_table
  - export TYPEORM_MIGRATIONS=./migration/*.ts


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install

unit_tests:
  stage: test
  script:
    - npm run test:cov

e2e_tests:
  stage: test
  script:
    - npm run test:e2e
